### ISSUE TITLE
PassengerPane hangs on SnowLeopard

### ISSUE THREAD

**Issue by karmajunkie** [Fingertips/passengerpane#20]
When I try to start PassengerPane it just hangs, with "Loading Passenger... (32-bit)" in the title bar.  This is the console output:

`9/23/09 11:44:44 AM    System Preferences[83845]   PrefPanePassenger#willSelect: NoMethodError: undefined method 'hidden=' for nil:NilClass
9/23/09 11:44:44 AM [0x0-0x4b84b8].com.apple.systempreferences  2009-09-23 11:44:44.477 System Preferences[83845:903] PrefPanePassenger#willSelect: NoMethodError: undefined method 'hidden=' for nil:NilClass
9/23/09 11:44:44 AM [0x0-0x4b84b8].com.apple.systempreferences      /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/PassengerPref.rb:250:in 'setup_passenger_warning!'
9/23/09 11:44:44 AM [0x0-0x4b84b8].com.apple.systempreferences      /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/PassengerPref.rb:52:in 'willSelect'
9/23/09 11:44:44 AM [0x0-0x4b84b8].com.apple.systempreferences      /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/PassengerPref.rb:250`

**Comment by alloy** [comment]
Could you please check if, for instance, this ticket helps you out?

http://github.com/alloy/passengerpane/issues/closed#issue/17

**Comment by karmajunkie** [comment]
Sadly, no help there... I tried building from source and it still hangs with the same messages in Console.

**Comment by alloy** [comment]
And /Library/Frameworks/RubyCocoa.framework doesn't exist for you either?

Also, what is your environment exactly?

**Comment by karmajunkie** [comment]
Nope, no RubyCocoa in /Library/Frameworks either.

`/usr/bin/ruby -v:
ruby 1.8.7 (2008-08-11 patchlevel 72) [universal-darwin10.0]`

`passenger-config --version --root:
 2.2.5`

`passenger-config --root
/Library/Ruby/Gems/1.8/gems/passenger-2.2.5`

Any other debug files or anything I should post?

**Comment by alloy** [comment]
Yes, on which OS X version are you exactly?

And just to be sure, could you check <code>~/Library/Frameworks</code> as well?

**Comment by karmajunkie** [comment]
Yeah, I guess my OS version would be important to know. :) I'm running 10.6.1.  Also using  Xcode 3.2, build 1610, and I don't have anything in ~/Library/Frameworks either.

**Comment by karmajunkie** [comment]
I do have a version of RubyCocoa installed in /System/Library/RubyCocoa.framework, it seems.  Could this be the culprit?

**Comment by karmajunkie** [comment]
I temporarily removed the version of RubyCocoa in /System/Library/Frameworks and reinstalled passengerpane, to no avail. the prefpane still stalls out whenever I try to load it.

**Comment by alloy** [comment]
No, the /System/Library/RubyCocoa.framework one comes with OS X and shouldn't be the problem. Don't forget to place it back :)

In case you upgraded from Leopard and had an older version of the pane installed, could you check if the old version might be in ~/Library/PreferencePanes whereas the new version would be in /Library/PreferencePanes?

Otherwise, I'm a bit at a loss on how to further debug this as I can't recreate the issue as of yet…

**Comment by jackpooley** [comment]
I have seem to have the same issue described by karmajunkie. RubyCocoa.framework is   neither /Library/Frameworks or ~/Library/Frameworks and I don't have any old version of the PrefPane instaled, I also tried to build from source unsuccessfully. Maybe you can use this system.log console output

```
Nov  5 14:03:41 Sol [0x0-0x100100].com.apple.systempreferences[0]: Thu Nov  5 14:03:41 Sol.local System Preferences[2322] <Error>: kCGErrorIllegalArgument: CGSDeviceCreate: Invalid window
Nov  5 14:03:41 Sol [0x0-0x100100].com.apple.systempreferences[0]: Thu Nov  5 14:03:41 Sol.local System Preferences[2322] <Error>: Failed to create window context device
Nov  5 14:03:41 Sol [0x0-0x100100].com.apple.systempreferences[0]: Thu Nov  5 14:03:41 Sol.local System Preferences[2322] <Error>: CGWindowContextCreate: failed to create context delegate.
Nov  5 14:03:41 Sol [0x0-0x100100].com.apple.systempreferences[0]: 2009-11-05 14:03:41.174 System Preferences[2322:903] _initWithWindowNumber: error creating graphics ctxt object for ctxt:0x19d27, window:0x0
Nov  5 14:03:41 Sol [0x0-0x100100].com.apple.systempreferences[0]: 2009-11-05 14:03:41.174 System Preferences[2322:903] CGPixelAccessLock failed!
Nov  5 14:03:41 Sol System Preferences[2322]: kCGErrorIllegalArgument: CGSDeviceCreate: Invalid window
Nov  5 14:03:41 Sol System Preferences[2322]: Failed to create window context device
Nov  5 14:03:41 Sol System Preferences[2322]: CGWindowContextCreate: failed to create context delegate.
Nov  5 14:03:41 Sol System Preferences[2322]: _initWithWindowNumber: error creating graphics ctxt object for ctxt:0x19d27, window:0x0
Nov  5 14:03:41 Sol System Preferences[2322]: CGPixelAccessLock failed!
```

I'm running 10.6.1, and passengerpane v1.3

**Comment by alloy** [comment]
When did you build from source, today? If so, can you give me details on what failed?

If you didn't build with the source of today, could you give it a try?

**Comment by alloy** [comment]
@jsmestad Did you build from source or install a release version?

**Comment by jackpooley** [comment]
I just tried again to re-build and install from the latest source and it now works like a charm thanks!

**Comment by boblu** [comment]
I also have this issue.
And my environment is
Snow Leopard 10.6.2

$ which ruby

/opt/local/bin/ruby

$ which gem

/opt/local/bin/gem

$ which httpd

/usr/sbin/httpd

$ which passenger-install-apache2-module 

/opt/local/bin/passenger-install-apache2-module

**Comment by alloy** [comment]
@boblu Sorry for the delay, I haven't received any mail about recent issue activity. Could you paste the console output?

**Comment by jasonroelofs** [comment]
So I'm running into this now as well. The one difference I have is that I'm trying to run Passenger under an rvm-installed Ruby. I was able to run the pane just fine with the system-installed Ruby.

**Comment by alloy** [comment]
@JamesDid you install RubyCocoa for this RVM-installed Ruby as well?
