### ISSUE TITLE
can't add apps in 1.3 on 10.6.1

### ISSUE THREAD

**Issue by bleything** [Fingertips/passengerpane#21]
I can't seem to add an application in the version 1.3 prefpane.  When I try, and click Apply, the following messages appear in Console.app:

```
10/6/09 6:08:08 AM  System Preferences[71276]   Applying changes to Rails application: /Users/ben/projects/teaching/permanent_record
10/6/09 6:08:08 AM  System Preferences[71276]   Starting Rails application: /Users/ben/projects/teaching/permanent_record
10/6/09 6:08:08 AM  System Preferences[71276]   Saving configuration: /private/etc/apache2/passenger_pane_vhosts/permanent-record.local.vhost.conf
10/6/09 6:08:08 AM  [0x0-0x116116].com.apple.systempreferences  2009-10-06 06:08:08.935 System Preferences[71276:903] Applying changes to Rails application: /Users/ben/projects/teaching/permanent_record
10/6/09 6:08:08 AM  [0x0-0x116116].com.apple.systempreferences  2009-10-06 06:08:08.937 System Preferences[71276:903] Starting Rails application: /Users/ben/projects/teaching/permanent_record
10/6/09 6:08:08 AM  [0x0-0x116116].com.apple.systempreferences  2009-10-06 06:08:08.937 System Preferences[71276:903] Saving configuration: /private/etc/apache2/passenger_pane_vhosts/permanent-record.local.vhost.conf
10/6/09 6:08:08 AM  authexec[71301] executing /usr/bin/ruby
10/6/09 6:08:09 AM  [0x0-0x116116].com.apple.systempreferences  /Library/Ruby/Site/1.8/universal-darwin10.0/rubycocoa.bundle: dlopen(/Library/Ruby/Site/1.8/universal-darwin10.0/rubycocoa.bundle, 9): no suitable image found.  Did find: (LoadError)
10/6/09 6:08:09 AM  [0x0-0x116116].com.apple.systempreferences      /Library/Ruby/Site/1.8/universal-darwin10.0/rubycocoa.bundle: no matching architecture in universal wrapper - /Library/Ruby/Site/1.8/universal-darwin10.0/rubycocoa.bundle
10/6/09 6:08:09 AM  [0x0-0x116116].com.apple.systempreferences      from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/osx/foundation.rb:8
10/6/09 6:08:09 AM  [0x0-0x116116].com.apple.systempreferences      from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/osx/cocoa.rb:8:in `require'
10/6/09 6:08:09 AM  [0x0-0x116116].com.apple.systempreferences      from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/osx/cocoa.rb:8
10/6/09 6:08:09 AM  [0x0-0x116116].com.apple.systempreferences      from /Users/ben/Library/PreferencePanes/Passenger.prefPane/Contents/Resources/config_installer.rb:3:in `require'
10/6/09 6:08:09 AM  [0x0-0x116116].com.apple.systempreferences      from /Users/ben/Library/PreferencePanes/Passenger.prefPane/Contents/Resources/config_installer.rb:3
10/6/09 6:08:34 AM  System Preferences[71276]   PrefPanePassenger#paneWillBecomeActive: Errno::ENOENT: No such file or directory - /private/etc/apache2/passenger_pane_vhosts/permanent-record.local.vhost.conf
10/6/09 6:08:34 AM  [0x0-0x116116].com.apple.systempreferences  2009-10-06 06:08:34.417 System Preferences[71276:903] PrefPanePassenger#paneWillBecomeActive: Errno::ENOENT: No such file or directory - /private/etc/apache2/passenger_pane_vhosts/permanent-record.local.vhost.conf
10/6/09 6:08:34 AM  [0x0-0x116116].com.apple.systempreferences      /Users/ben/Library/PreferencePanes/Passenger.prefPane/Contents/Resources/passenger_application.rb:218:in `read'
10/6/09 6:08:34 AM  [0x0-0x116116].com.apple.systempreferences      /Users/ben/Library/PreferencePanes/Passenger.prefPane/Contents/Resources/passenger_application.rb:218:in `load_data_from_vhost_file'
10/6/09 6:08:34 AM  [0x0-0x116116].com.apple.systempreferences      /Users/ben/Library/PreferencePanes/Passenger.prefPane/Contents/Resources/passenger_application.rb:156:in `reload!'
10/6/09 6:08:34 AM  [0x0-0x116116].com.apple.systempreferences      /Users/ben/Library/PreferencePanes/Passenger.prefPane/Contents/Resources/passenger_pref.rb:269:in `reload_appications!'
10/6/09 6:08:34 AM  [0x0-0x116116].com.apple.systempreferences      /Users/ben/Library/PreferencePanes/Passenger.prefPane/Contents/Frameworks/RubyCocoa.framework/Resources/ruby/osx/objc/oc_attachments.rb:1132:in `each'
10/6/09 6:08:34 AM  [0x0-0x116116].com.apple.systempreferences      /Users/ben/Library/PreferencePanes/Passenger.prefPane/Contents/Resources/passenger_pref.rb:269:in `reload_appications!'
10/6/09 6:08:34 AM  [0x0-0x116116].com.apple.systempreferences      /Users/ben/Library/PreferencePanes/Passenger.prefPane/Contents/Resources/passenger_pref.rb:60:in `willSelect'
10/6/09 6:08:34 AM  [0x0-0x116116].com.apple.systempreferences      /Users/ben/Library/PreferencePanes/Passenger.prefPane/Contents/Resources/passenger_pref.rb:54:in `paneWillBecomeActive'
10/6/09 6:08:34 AM  System Preferences[71276]   No such file or directory - /private/etc/apache2/passenger_pane_vhosts/permanent-record.local.vhost.conf
10/6/09 6:08:34 AM  [0x0-0x116116].com.apple.systempreferences  2009-10-06 06:08:34.418 System Preferences[71276:903] No such file or directory - /private/etc/apache2/passenger_pane_vhosts/permanent-record.local.vhost.conf
```

This is with completely stock built-in Ruby and whatnot.  Let me know if there's any other information I can provide.

**Comment by alloy** [comment]
Hrmm, it seems as if your system RubyCocoa is a bit messed up… Could you see if Ruby is able to load it at all like so?

```
$ /usr/bin/ruby -r osx/cocoa -e "p OSX::RUBYCOCOA_VERSION" 
"0.13.2"
```

**Comment by bleything** [comment]
Nope :(

```
[06:36:36] ben@folio (master) 
~/projects/teaching/permanent_record $ /usr/bin/ruby -r osx/cocoa -e "p OSX::RUBYCOCOA_VERSION"
/Library/Ruby/Site/1.8/universal-darwin10.0/rubycocoa.bundle: dlopen(/Library/Ruby/Site/1.8/universal-darwin10.0/rubycocoa.bundle, 9): no suitable image found.  Did find: (LoadError)
    /Library/Ruby/Site/1.8/universal-darwin10.0/rubycocoa.bundle: no matching architecture in universal wrapper - /Library/Ruby/Site/1.8/universal-darwin10.0/rubycocoa.bundle
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/osx/foundation.rb:8
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/osx/cocoa.rb:8:in `require'
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/osx/cocoa.rb:8
```

I'm at a loss for how this could have happened.  Should I just reinstall RubyCocoa and see what happens?

**Comment by alloy** [comment]
I think you still have an installed RubyCocoa which remains after an upgrade :-/

Can you remove:
1. /Library/Frameworks/RubyCocoa.framework
2. /Library/Ruby/Site/1.8/universal-darwin10.0/rubycocoa.bundle

This should make it pick up the system one again. I hope ;-)

**Comment by bleything** [comment]
that's the confusing part... I didn't do an upgrade.  I did a fresh install then manually migrated my homedir.

At any rate, your suggestion did the trick.  Deleted those files, and all is well.  Thanks :)

**Comment by alloy** [comment]
Oh my, that is interesting indeed. But I have no other explanations up my sleeve :)

Glad to hear it works now though!
