### ISSUE TITLE
Can't remove a site using the [-] key

### ISSUE THREAD

**Issue by walterdavis** [Fingertips/passengerpane#39]
If I remove a site using the [-] button, it disappears from the list, but if I close the preference pane and open it back up, it's still there.

**Comment by alloy** [comment]
Could you check the logs (Console.app) to see if anything interesting gets print out when removing the application?

**Comment by walterdavis** [comment]
Here's every little thing related to passenger from my system log:

```
2/4/10 1:51:28 PM System Preferences[1693] Saving configuration: /private/etc/apache2/passenger_pane_vhosts/frames.local.vhost.conf 
2/4/10 1:51:28 PM [0x0-0x1c01c].com.apple.systempreferences[1693] 2010-02-04 13:51:28.822 ruby[1779:913] Will create directory: /private/etc/apache2/passenger_pane_vhosts 
2/4/10 1:51:28 PM [0x0-0x1c01c].com.apple.systempreferences[1693] 2010-02-04 13:51:28.823 ruby[1779:913] Will try to append passenger pane vhosts conf to: /private/etc/apache2/httpd.conf 
2/4/10 1:51:28 PM [0x0-0x1c01c].com.apple.systempreferences[1693] 2010-02-04 13:51:28.916 ruby[1779:913] Will write vhost file: /private/etc/apache2/passenger_pane_vhosts/frames.local.vhost.conf 
2/4/10 7:12:46 PM System Preferences[1667] Removing applications: --- 
- config_path: /private/etc/apache2/passenger_pane_vhosts/frames.local.vhost.conf
  app_type: rails
  environment: development
  aliases: ""
  host: frames.local
  user_defined_data: "  <Directory \"/Library/WebServer/Documents/frames/public\">\n    Order allow,deny\n    Allow from all\n  </Directory>"
  vhostname: "*:80"
  path: /Library/WebServer/Documents/frames

2/4/10 7:12:47 PM [0x0-0x21021].com.apple.systempreferences[1667] 2010-02-04 19:12:47.370 ruby[36024:913] Will remove vhost file: /private/etc/apache2/passenger_pane_vhosts/frames.local.vhost.conf 
2/4/10 7:17:38 PM System Preferences[1667] PrefPanePassenger#paneWillBecomeActive: Errno::ENOENT: No such file or directory - /private/etc/apache2/passenger_pane_vhosts/frames.local.vhost.conf 
2/4/10 7:17:38 PM System Preferences[1667] No such file or directory - /private/etc/apache2/passenger_pane_vhosts/frames.local.vhost.conf 
2/4/10 7:17:40 PM System Preferences[1667] Removing applications: --- 
- config_path: /private/etc/apache2/passenger_pane_vhosts/frames.local.vhost.conf
  app_type: rails
  environment: development
  aliases: ""
  host: frames.local
  user_defined_data: "  <Directory \"/Library/WebServer/Documents/frames/public\">\n    Order allow,deny\n    Allow from all\n  </Directory>"
  vhostname: "*:80"
  path: /Library/WebServer/Documents/frames

2/4/10 7:17:38 PM [0x0-0x21021].com.apple.systempreferences[1667]  /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/passenger_application.rb:218:in `read' 
2/4/10 7:17:38 PM [0x0-0x21021].com.apple.systempreferences[1667]  /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/passenger_application.rb:218:in `load_data_from_vhost_file' 
2/4/10 7:17:38 PM [0x0-0x21021].com.apple.systempreferences[1667]  /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/passenger_application.rb:156:in `reload!' 
2/4/10 7:17:38 PM [0x0-0x21021].com.apple.systempreferences[1667]  /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/passenger_pref.rb:269:in `reload_appications!' 
2/4/10 7:17:38 PM [0x0-0x21021].com.apple.systempreferences[1667]  /Library/PreferencePanes/Passenger.prefPane/Contents/Frameworks/RubyCocoa.framework/Resources/ruby/osx/objc/oc_attachments.rb:1132:in `each' 
2/4/10 7:17:38 PM [0x0-0x21021].com.apple.systempreferences[1667]  /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/passenger_pref.rb:269:in `reload_appications!' 
2/4/10 7:17:38 PM [0x0-0x21021].com.apple.systempreferences[1667]  /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/passenger_pref.rb:60:in `willSelect' 
2/4/10 7:17:38 PM [0x0-0x21021].com.apple.systempreferences[1667]  /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/passenger_pref.rb:54:in `paneWillBecomeActive' 
2/4/10 7:17:40 PM [0x0-0x21021].com.apple.systempreferences[1667] 2010-02-04 19:17:40.250 ruby[36106:913] Will remove vhost file: /private/etc/apache2/passenger_pane_vhosts/frames.local.vhost.conf 
2/4/10 7:17:40 PM [0x0-0x21021].com.apple.systempreferences[1667] /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/config_uninstaller.rb:32:in `delete': No such file or directory - /private/etc/apache2/passenger_pane_vhosts/frames.local.vhost.conf (Errno::ENOENT) 
2/4/10 7:17:40 PM [0x0-0x21021].com.apple.systempreferences[1667]  from /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/config_uninstaller.rb:32:in `remove_vhost_conf' 
2/4/10 7:17:40 PM [0x0-0x21021].com.apple.systempreferences[1667]  from /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/config_uninstaller.rb:46:in `uninstall!' 
2/4/10 7:17:40 PM [0x0-0x21021].com.apple.systempreferences[1667]  from /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/config_uninstaller.rb:44:in `each' 
2/4/10 7:17:40 PM [0x0-0x21021].com.apple.systempreferences[1667]  from /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/config_uninstaller.rb:44:in `uninstall!' 
2/4/10 7:17:40 PM [0x0-0x21021].com.apple.systempreferences[1667]  from /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/config_uninstaller.rb:54 
2/4/10 7:18:00 PM System Preferences[1667] PrefPanePassenger#paneWillBecomeActive: Errno::ENOENT: No such file or directory - /private/etc/apache2/passenger_pane_vhosts/frames.local.vhost.conf 
2/4/10 7:18:00 PM System Preferences[1667] No such file or directory - /private/etc/apache2/passenger_pane_vhosts/frames.local.vhost.conf 
2/4/10 7:18:00 PM [0x0-0x21021].com.apple.systempreferences[1667]  /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/passenger_application.rb:218:in `read' 
2/4/10 7:18:00 PM [0x0-0x21021].com.apple.systempreferences[1667]  /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/passenger_application.rb:218:in `load_data_from_vhost_file' 
2/4/10 7:18:00 PM [0x0-0x21021].com.apple.systempreferences[1667]  /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/passenger_application.rb:156:in `reload!' 
2/4/10 7:18:00 PM [0x0-0x21021].com.apple.systempreferences[1667]  /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/passenger_pref.rb:269:in `reload_appications!' 
2/4/10 7:18:00 PM [0x0-0x21021].com.apple.systempreferences[1667]  /Library/PreferencePanes/Passenger.prefPane/Contents/Frameworks/RubyCocoa.framework/Resources/ruby/osx/objc/oc_attachments.rb:1132:in `each' 
2/4/10 7:18:00 PM [0x0-0x21021].com.apple.systempreferences[1667]  /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/passenger_pref.rb:269:in `reload_appications!' 
2/4/10 7:18:00 PM [0x0-0x21021].com.apple.systempreferences[1667]  /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/passenger_pref.rb:60:in `willSelect' 
2/4/10 7:18:00 PM [0x0-0x21021].com.apple.systempreferences[1667]  /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/passenger_pref.rb:54:in `paneWillBecomeActive' 
2/4/10 7:18:00 PM [0x0-0x21021].com.apple.systempreferences[1667]  /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/passenger_application.rb:218 
2/4/10 7:18:23 PM System Preferences[1667] Removing applications: --- 
- config_path: /private/etc/apache2/passenger_pane_vhosts/frames.local.vhost.conf
  app_type: rails
  environment: development
  aliases: ""
  host: frames.local
  user_defined_data: "  <Directory \"/Library/WebServer/Documents/frames/public\">\n    Order allow,deny\n    Allow from all\n  </Directory>"
  vhostname: "*:80"
  path: /Library/WebServer/Documents/frames

2/4/10 7:18:24 PM [0x0-0x21021].com.apple.systempreferences[1667] 2010-02-04 19:18:24.171 ruby[36119:913] Will remove vhost file: /private/etc/apache2/passenger_pane_vhosts/frames.local.vhost.conf 
2/4/10 7:18:24 PM [0x0-0x21021].com.apple.systempreferences[1667] /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/config_uninstaller.rb:32:in `delete': No such file or directory - /private/etc/apache2/passenger_pane_vhosts/frames.local.vhost.conf (Errno::ENOENT) 
2/4/10 7:18:24 PM [0x0-0x21021].com.apple.systempreferences[1667]  from /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/config_uninstaller.rb:32:in `remove_vhost_conf' 
2/4/10 7:18:24 PM [0x0-0x21021].com.apple.systempreferences[1667]  from /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/config_uninstaller.rb:46:in `uninstall!' 
2/4/10 7:18:24 PM [0x0-0x21021].com.apple.systempreferences[1667]  from /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/config_uninstaller.rb:44:in `each' 
2/4/10 7:18:24 PM [0x0-0x21021].com.apple.systempreferences[1667]  from /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/config_uninstaller.rb:44:in `uninstall!' 
2/4/10 7:18:24 PM [0x0-0x21021].com.apple.systempreferences[1667]  from /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/config_uninstaller.rb:54 
2/4/10 7:33:10 PM System Preferences[1667] PrefPanePassenger#paneWillBecomeActive: Errno::ENOENT: No such file or directory - /private/etc/apache2/passenger_pane_vhosts/frames.local.vhost.conf 
2/4/10 7:33:10 PM System Preferences[1667] No such file or directory - /private/etc/apache2/passenger_pane_vhosts/frames.local.vhost.conf 
2/4/10 7:33:10 PM [0x0-0x21021].com.apple.systempreferences[1667]  /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/passenger_application.rb:218:in `read' 
2/4/10 7:33:10 PM [0x0-0x21021].com.apple.systempreferences[1667]  /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/passenger_application.rb:218:in `load_data_from_vhost_file' 
2/4/10 7:33:10 PM [0x0-0x21021].com.apple.systempreferences[1667]  /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/passenger_application.rb:156:in `reload!' 
2/4/10 7:33:10 PM [0x0-0x21021].com.apple.systempreferences[1667]  /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/passenger_pref.rb:269:in `reload_appications!' 
2/4/10 7:33:10 PM [0x0-0x21021].com.apple.systempreferences[1667]  /Library/PreferencePanes/Passenger.prefPane/Contents/Frameworks/RubyCocoa.framework/Resources/ruby/osx/objc/oc_attachments.rb:1132:in `each' 
2/4/10 7:33:10 PM [0x0-0x21021].com.apple.systempreferences[1667]  /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/passenger_pref.rb:269:in `reload_appications!' 
2/4/10 7:33:10 PM [0x0-0x21021].com.apple.systempreferences[1667]  /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/passenger_pref.rb:60:in `willSelect' 
2/4/10 7:33:10 PM [0x0-0x21021].com.apple.systempreferences[1667]  /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/passenger_pref.rb:54:in `paneWillBecomeActive' 
2/4/10 7:33:10 PM [0x0-0x21021].com.apple.systempreferences[1667]  /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/passenger_application.rb:218 
2/4/10 7:33:24 PM System Preferences[1667] PrefPanePassenger#paneWillBecomeActive: Errno::ENOENT: No such file or directory - /private/etc/apache2/passenger_pane_vhosts/frames.local.vhost.conf 
2/4/10 7:33:24 PM System Preferences[1667] No such file or directory - /private/etc/apache2/passenger_pane_vhosts/frames.local.vhost.conf 
2/4/10 7:33:24 PM [0x0-0x21021].com.apple.systempreferences[1667]  /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/passenger_application.rb:218:in `read' 
2/4/10 7:33:24 PM [0x0-0x21021].com.apple.systempreferences[1667]  /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/passenger_application.rb:218:in `load_data_from_vhost_file' 
2/4/10 7:33:24 PM [0x0-0x21021].com.apple.systempreferences[1667]  /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/passenger_application.rb:156:in `reload!' 
2/4/10 7:33:24 PM [0x0-0x21021].com.apple.systempreferences[1667]  /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/passenger_pref.rb:269:in `reload_appications!' 
2/4/10 7:33:24 PM [0x0-0x21021].com.apple.systempreferences[1667]  /Library/PreferencePanes/Passenger.prefPane/Contents/Frameworks/RubyCocoa.framework/Resources/ruby/osx/objc/oc_attachments.rb:1132:in `each' 
2/4/10 7:33:24 PM [0x0-0x21021].com.apple.systempreferences[1667]  /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/passenger_pref.rb:269:in `reload_appications!' 
2/4/10 7:33:24 PM [0x0-0x21021].com.apple.systempreferences[1667]  /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/passenger_pref.rb:60:in `willSelect' 
2/4/10 7:33:24 PM [0x0-0x21021].com.apple.systempreferences[1667]  /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/passenger_pref.rb:54:in `paneWillBecomeActive' 
2/4/10 7:33:24 PM [0x0-0x21021].com.apple.systempreferences[1667]  /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/passenger_application.rb:218 
2/4/10 7:35:19 PM System Preferences[1667] PrefPanePassenger#paneWillBecomeActive: Errno::ENOENT: No such file or directory - /private/etc/apache2/passenger_pane_vhosts/frames.local.vhost.conf 
2/4/10 7:35:19 PM System Preferences[1667] No such file or directory - /private/etc/apache2/passenger_pane_vhosts/frames.local.vhost.conf 
2/4/10 7:35:19 PM [0x0-0x21021].com.apple.systempreferences[1667]  /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/passenger_application.rb:218:in `read' 
2/4/10 7:35:19 PM [0x0-0x21021].com.apple.systempreferences[1667]  /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/passenger_application.rb:218:in `load_data_from_vhost_file' 
2/4/10 7:35:19 PM [0x0-0x21021].com.apple.systempreferences[1667]  /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/passenger_application.rb:156:in `reload!' 
2/4/10 7:35:19 PM [0x0-0x21021].com.apple.systempreferences[1667]  /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/passenger_pref.rb:269:in `reload_appications!' 
2/4/10 7:35:19 PM [0x0-0x21021].com.apple.systempreferences[1667]  /Library/PreferencePanes/Passenger.prefPane/Contents/Frameworks/RubyCocoa.framework/Resources/ruby/osx/objc/oc_attachments.rb:1132:in `each' 
2/4/10 7:35:19 PM [0x0-0x21021].com.apple.systempreferences[1667]  /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/passenger_pref.rb:269:in `reload_appications!' 
2/4/10 7:35:19 PM [0x0-0x21021].com.apple.systempreferences[1667]  /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/passenger_pref.rb:60:in `willSelect' 
2/4/10 7:35:19 PM [0x0-0x21021].com.apple.systempreferences[1667]  /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/passenger_pref.rb:54:in `paneWillBecomeActive' 
2/4/10 7:35:19 PM [0x0-0x21021].com.apple.systempreferences[1667]  /Library/PreferencePanes/Passenger.prefPane/Contents/Resources/passenger_application.rb:218 
```

Please let me know if there are any specific things you would like me to try.

One other thing I noted was this:
1. Install pref pane by double-clicking. 
2. Choose "for all users" when asked.
3. System Preferences tells me that I will be asked for my password when I do so, but then NEVER ASKS FOR IT.
4. The fun noted above begins.

Passenger worked fine through all this. I put an app in from my Documents folder, then when I discovered that Paperclip was having trouble saving files there, I deleted the site, moved the entire rails site folder to the /Library/WebServer/Documents folder and added it back from there. After further permissions fiddling, it seemed to work pretty well. I did continue to have trouble saving files from Paperclip -- the save action would seem to hang -- never redirect to index or view. The files would be saved, though. A reload would show them there.

**Comment by walterdavis** [comment]
Mac OS X 10.5 + all patches, forgot to mention.

**Comment by walterdavis** [comment]
Here's some more goodies from Console, these are from httpd and might be related.

```
2/4/10 1:35:08 PM com.apple.launchd[1] (org.apache.httpd) Unknown key: SHAuthorizationRight 
2/4/10 1:48:11 PM com.apple.launchd[1] (org.apache.httpd) Unknown key: SHAuthorizationRight 
2/4/10 1:48:30 PM org.apache.httpd[26] httpd: Could not reliably determine the server's fully qualified domain name, using al.local for ServerName 
2/4/10 1:48:32 PM org.apache.httpd[133] httpd: Could not reliably determine the server's fully qualified domain name, using al.local for ServerName 
2/4/10 1:51:28 PM [0x0-0x1c01c].com.apple.systempreferences[1693] 2010-02-04 13:51:28.823 ruby[1779:913] Will try to append passenger pane vhosts conf to: /private/etc/apache2/httpd.conf 
2/4/10 1:51:29 PM com.apple.launchd[1] (org.apache.httpd) Unknown key: SHAuthorizationRight 
2/4/10 2:45:02 PM com.apple.launchd[1] (org.apache.httpd) Unknown key: SHAuthorizationRight 
2/4/10 2:45:15 PM org.apache.httpd[27] httpd: Could not reliably determine the server's fully qualified domain name, using al.local for ServerName 
2/4/10 2:51:27 PM com.apple.launchd[1] (org.apache.httpd) Unknown key: SHAuthorizationRight 
2/4/10 3:36:18 PM com.apple.launchd[1] (org.apache.httpd[1688]) Stray process with PGID equal to this dead job: PID 1708 PPID 1 ruby 
2/4/10 3:36:18 PM com.apple.launchd[1] (org.apache.httpd[1688]) Stray zombie process with PGID equal to this dead job: PID 1710 PPID 1708 ruby 
2/4/10 3:36:20 PM com.apple.launchd[1] (org.apache.httpd) Unknown key: SHAuthorizationRight 
2/4/10 7:12:47 PM com.apple.launchd[1] (org.apache.httpd) Unknown key: SHAuthorizationRight 
2/4/10 7:35:56 PM com.apple.launchd[1] (org.apache.httpd) Unknown key: SHAuthorizationRight
```

Thanks again,

Walter

**Comment by alloy** [comment]
Sorry for the lack of updates, I've been sick the last few weeks…

So it complains that the vhost file doesn't exist at: /private/etc/apache2/passenger_pane_vhosts/frames.local.vhost.conf. Does it?

**Comment by walterdavis** [comment]
No, it's not there. Further, it did append its configuration to the end of the main httpd.conf file, and then could not seem to remove that when it was asked to remove the site through the Preference Pane.
